name: Android Feature Branch CI
## Workflow Goals
#1. Run ktlint on all push
#2. Run detekt on all push
#3. Run Unit And Instrumentation tests
#4. Run tes coverage

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release'

jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


  ktlint:
    runs-on: ubuntu-18.04
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - run: brew install ktlint
      - name: Run ktlint
        run: ./gradlew detektAll

  detekt:
    needs: [setup,ktlint]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: brew install ktlint
      - name: Run ktlint
        run: ./gradlew ktlintDebugCheck

  test:
    needs: [setup,ktlint,detekt]
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest --stacktrace

  build:
    runs-on: ubuntu-18.04
    needs: [setup,ktlint,detekt,test]
    steps:
      - actions/checkout@v2
      - name: Build Project
        run: ./gradlew assembleDebug