name: ktlint - Android Plugin

on:
  pull_request:
    paths:
      - .github/workflows/detekt.yml
      - 'src/**/*.k'
      - '**.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install ktlint
      - name: Run ktlint
        run: ./gradlew detektAll